# Generated by Django 5.1.3 on 2024-12-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apP', '0003_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributorCompanyDemandForProduct',
        ),
    ]
