# Generated by Django 5.1.3 on 2024-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apP', '0004_delete_distributorcompanydemandforproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDemand',
            fields=[
                ('p_demand_id', models.AutoField(primary_key=True, serialize=False)),
                ('demandamount', models.DecimalField(db_column='DemandAmount', decimal_places=2, max_digits=10)),
                ('ton', models.DecimalField(blank=True, db_column='TON', decimal_places=2, max_digits=10, null=True)),
                ('mon', models.DecimalField(blank=True, db_column='MON', decimal_places=2, max_digits=10, null=True)),
                ('kg', models.DecimalField(blank=True, db_column='KG', decimal_places=2, max_digits=10, null=True)),
                ('demand_date_time', models.DateTimeField(db_column='Demand_Date_Time')),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=100, null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=255, null=True)),
                ('season', models.CharField(blank=True, db_column='SEASON', max_length=50, null=True)),
                ('price_should_be', models.DecimalField(blank=True, db_column='Price_Should_be', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'p_demand',
                'managed': False,
            },
        ),
    ]
