# Generated by Django 5.1.3 on 2024-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apP', '0005_pdemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
