# Generated by Django 5.1.3 on 2024-12-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apP', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
    ]
